services:

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui

    #restart: unless-stopped

    ports:
      - "3000:8080"

    environment:
      WEBUI_SECRET_KEY: "abc123."

      # PostgreSQL + pgvector
      VECTOR_DB: pgvector
      PGVECTOR_DB_URL: "postgresql://rag:abc123.@pgvector:5432/rag"

      # Embeddings mediante Ollama
      RAG_EMBEDDING_ENGINE: ollama
      RAG_EMBEDDING_MODEL: nomic-embed-text-v2-moe

      # Ollama
      OLLAMA_BASE_URLS: "http://ollama:11434"
      
    volumes:
      - ./openwebui/data:/app/backend/data

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    depends_on:
      pgvector:
        condition: service_healthy
      ollama:
        condition: service_started

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm

    #restart: unless-stopped

    ports:
      - "3001:3001"

    environment:
      STORAGE_DIR: /app/server/storage
      JWT_SECRET: "abc123."
      
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./anythingllm/storage:/app/server/storage

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

    depends_on:
      pgvector:
        condition: service_healthy
      ollama:
        condition: service_started

  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector

    #restart: unless-stopped

    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: "abc123."

    volumes:
      - ./pgvector/data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d rag"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama

    environment:
      OLLAMA_MODELS: /models
      OLLAMA_HOST: 0.0.0.0:11434
      OLLAMA_VULKAN: "1"
      OLLAMA_IGPU_ENABLE: "1"

    volumes:
      - /media/javierfp/89693743-64d4-4535-8ef6-30d13cdb6322/MODELOS_IA:/models
      - ollama_state:/root/.ollama

    devices:
      - /dev/dri:/dev/dri

    ports:
      - "11434:11434"

volumes:
  ollama_state:
